# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 06:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Book Title', max_length=500)),
                ('description', models.TextField(help_text='Enter Book Description')),
                ('author', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('published_by', models.CharField(blank=True, help_text='Enter Book publisher name', max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Enter Book Published Date', null=True)),
                ('price', models.IntegerField(help_text='Enter Book Price')),
                ('discount', models.IntegerField(default=0, help_text='Enter Discount Value')),
                ('count', models.IntegerField(help_text='Enter count of book')),
                ('is_in_stock', models.BooleanField(default=True)),
                ('delievery_charge', models.IntegerField(default=0, help_text='Enter delievery charge value if applicable')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Book Category Name', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='The hyphenated category name in all lowercase and unique', max_length=255, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Enter SubCategory Name', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='The hyphenated Subcategory name in all lowercase and unique', max_length=255, populate_from='subcategory_name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.SubCategory'),
        ),
    ]
