# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
